<?xml version="1.0" encoding="utf-8"?><Database Name="SonGaming" Class="SonGamingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sonsiho\sonsiho;Initial Catalog=SonGaming;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SonGamingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ADMIN" Member="ADMINs">
    <Type Name="ADMIN">
      <Column Name="username" Type="System.String" DbType="NVarChar(250) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="masanpham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mansx" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maloai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tensanpham" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="giaban" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaycapnhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="hinhsanpham" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="thongtin" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="SANPHAM_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="masanpham" OtherKey="masanpham" Type="CHITIETHOADON" />
      <Association Name="LOAISANPHAM_SANPHAM" Member="LOAISANPHAM" ThisKey="maloai" OtherKey="maloai" Type="LOAISANPHAM" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="NHASANXUAT_SANPHAM" Member="NHASANXUAT" ThisKey="mansx" OtherKey="mansx" Type="NHASANXUAT" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="mahoadon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masanpham" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dongia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="SANPHAM_CHITIETHOADON" Member="SANPHAM" ThisKey="masanpham" OtherKey="masanpham" Type="SANPHAM" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="HOADON" ThisKey="mahoadon" OtherKey="mahoadon" Type="HOADON" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="makh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenkhachhang" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="taikhoan" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="matkhau" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="sodienthoai" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="KHACHHANG_HOADON" Member="HOADONs" ThisKey="makh" OtherKey="makh" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.LOAISANPHAM" Member="LOAISANPHAMs">
    <Type Name="LOAISANPHAM">
      <Column Name="maloai" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenloai" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="LOAISANPHAM_SANPHAM" Member="SANPHAMs" ThisKey="maloai" OtherKey="maloai" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.NHASANXUAT" Member="NHASANXUATs">
    <Type Name="NHASANXUAT">
      <Column Name="mansx" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tennsx" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="NHASANXUAT_SANPHAM" Member="SANPHAMs" ThisKey="mansx" OtherKey="mansx" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.DONHANG" Member="DONHANGs">
    <Type Name="DONHANG">
      <Column Name="mahoadon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenkhachhang" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ngaydat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tinhtrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTDH" Member="CTDHs">
    <Type Name="CTDH">
      <Column Name="mahoadon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="masanpham" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tensanpham" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="hinhsanpham" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dongia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Tổng Tiền]" Member="Tổng_Tiền" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="mahoadon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="makh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaydat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tinhtrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="mahoadon" OtherKey="mahoadon" Type="CHITIETHOADON" />
      <Association Name="KHACHHANG_HOADON" Member="KHACHHANG" ThisKey="makh" OtherKey="makh" Type="KHACHHANG" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>